### ISSUE TITLE
Why a return after a comment?

### ISSUE THREAD

**Issue by LettError** [typesupply/feaPyFoFum#4]
The comment method of writer seems to add an extra line after a comment. But it is not obvious to me in the code where this happens (or why). Obviously not a big problem, just curious. 

```
ss01Writer = writer.feature("ss01")
ss01Writer.comment("This is a comment")
```

```
feature ss01 {
    # This is a comment

    sub a by b;
    sub c by d;
} ss01;
```

**Comment by typesupply** [comment]
I tried to follow [this](http://opentypecookbook.com/style-guide.html). Sometimes I use a return, sometimes I don't. I was probably too lazy to make the formatter smart enough to know when to do it and when not to.

**Comment by LettError** [comment]
But you wrote that! :)
