### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by typesupply** [typesupply/feaPyFoFum#9]
Add a way to create a namespace that will be used for all executions. This would allow for code to be reusable. Something like this:

```
# >>> global
# allGlyphs = [name for name in sorted(font.keys()) if name != ".notdef"
# <<<
```

Then later, in a `blah` feature block:

```
feature blah {
# >>>
# for name in allGlyphs:
#     ...
# <<<
} blah;
```

**Comment by typemytype** [comment]
it is pure python inside, so actually it works like functions and the function scopes.

so this should actually already work:

```
# >>>
# global allGlyphs
# allGlyphs = [name for name in sorted(font.keys()) if name != ".notdef"
# <<<
```

**Comment by typesupply** [comment]
I've been experimenting with this and the use of `global` doesn't work. I've found an easier solution: execute all code blocks within  single .fea file with the same namespace.
